
apiVersion: v1 #version of the API to use
kind: Pod #What kind of object we're deploying
metadata: #information about our object we're deploying
  name: php7
spec: #specifications for our object
  containers:
  - name: php-container #the name of the container within the pod
    image: webdevops/php-apache #which container image should be pulled
    ports:
    - containerPort: 80 #the port of the container within the pod
